### ISSUE TITLE
Decreasing `final_weight` in `smt.chsearch`

### ISSUE THREAD

**Issue by agievich** [ranea/CASCADA#10]
In the module `smt.chsearch`, a SMT solver searches for characteristics whose weights lie in the interval `[target_weight, final_weight]`. Whenever a new suitable characteristic is found, `final_weigth` is updated with
```
new_final_weight = int(math.ceil(ch_found.ch_weight + self._error))
```
(see `ChFinder._new_final_weight()`). Here `ch_found` is the found characteristic, `ch_found.ch_weight` is its weight, and `_error` is the sum of fractional parts of weights of all involved operations. 

It seems that `new_final_weight` can be refined as follows:
```
new_final_weight = int(math.ceil(ch_found.ch_weight))
```
Indeed, since the characteristic of weight `ch_weight` exists, the minimum weight does not exceed `ceil(ch_weight)`. The bound `ceil(ch_weight + _error)` is less precise.

**Comment by agievich** [comment]
Additional comment. In our experiments with CASCADA, after changing `ChFinder._new_final_weight()` we detected an error in 
`round_based_ch_search()` when completing the search for characteristics. It seems that the line 
```
min_target_weight = min(min_target_weight, target_weight)
```
has to be replaced with
```
if target_weight != None and target_weight < min_target_weight:
	min_target_weight = target_weight
```

**Comment by ranea** [comment]
If you don't add `self._error` in the line `new_final_weight = int(math.ceil(ch_found.ch_weight + self._error))`, the problem is that you might miss the optimal characteristic in the search.

For example, assume `self._error` is 2. When searching for `target_weight` 1, assume you found a characteristic with `ch_found.ch_weight` 1 (i.e., with characteristic error 0) . However, you still need to search for `target_weight` 2 if you want to be sure that you don't miss a possible optimal characteristic, since it might be possible that when searching for `target_weight` 2 you find a characteristic with `ch_found.ch_weight` 0 (i.e., with characteristic error 2).

Regarding the error in the second comment, does this also affect if the line `new_final_weight = int(math.ceil(ch_found.ch_weight + self._error))` is used?

**Comment by agievich** [comment]
Perhaps I misunderstood how CASCADA searches for `target_weight`. As far as I got,

1. CASCADA runs over the operations of the target block cipher and rounds (`floor`) their weights.

2. CASCADA prepares an SMT problem for `target_weight` with rounded weights of the operations. 

3. CASCADA runs over the solutions found and converts them to characteristics. For each characteristic (`ch_found`) CASCADA restores fractional parts of weights of the operations involved and determines the actual weight of the characteristic (`ch_found.ch_weight`, note that `ch_found.ch_weight >= target_weight`).

Your example (`target_weight = 1`, `ch_found.ch_weight = 0`) does not match the reconstruction above. What is wrong?

**Comment by agievich** [comment]
> Regarding the error in the second comment, does this also affect if the line new_final_weight = int(math.ceil(ch_found.ch_weight + self._error)) is used?

I have experimented with GOST (see #11). With 
```
new_final_weight = int(math.ceil(ch_found.ch_weight + self._error)) 
```
I was unable to complete experiments and get to the problem lines of code every time I used an S-box with a non-integer weight.

An example:
```
from cascada.differential.difference import XorDiff
from cascada.smt.chsearch import ChModelAssertType, PrintingMode 
from cascada.smt.chsearch import round_based_ch_search
from cascada.primitives import gost

Gost = gost.get_GOST_instance(gost.SBOXES_CB) 
Gost.test()

def gost_da(initial_num_rounds, final_num_rounds, initial_weight=0):
  iterator = round_based_ch_search(
    Gost, initial_num_rounds, final_num_rounds, 
    XorDiff, ChModelAssertType.ValidityAndWeight, "btor",
    extra_chfinder_args={
      "exclude_zero_input_prop": True, 
      "printing_mode": PrintingMode.WeightsAndSrepr,
      "solver_seed": 0},
    extra_findnextchweight_args={"initial_weight": initial_weight}
  )
  for (num_rounds, ch) in iterator:
    print(num_rounds, ":", ch.srepr())

gost_da(6, 6)
```

**Comment by ranea** [comment]
The problem here lies in the difference between bit-vector weights and decimal weights, which is a source of confusion. I'll try to explain.

> Perhaps I misunderstood how CASCADA searches for `target_weight`. As far as I got,
> 
>     1. CASCADA runs over the operations of the target block cipher and rounds (`floor`) their weights.
CASCADA does not rounds the weight. For simplicity let's only consider differential XOR cryptanalysis. For every operation, CASCADA assigns an XOR model, and as a result there are 3 weights associated to the propagation of differences through every operation: the [bv_weight](https://ranea.github.io/CASCADA/_modules/cascada/abstractproperty/opmodel.html#OpModel.bv_weight), which is the weight used in the SMT modelling, the [decimal_weight](https://ranea.github.io/CASCADA/_modules/cascada/abstractproperty/opmodel.html#OpModel.decimal_weight), which is the weight used when computing `ch_found.ch_weight` and it is a better approximation that `bv_weight`, and finally `empirical_weight` (but this weight is for the whole characteristic and does not play a role in this issue).
> 
>     2. CASCADA prepares an SMT problem for `target_weight` with rounded weights of the operations.
CASCADA uses the `bv_weight` of every property model in a characteristic to represent the characteristic weight in a SMT problem. In some cases, the `bv_weight` is the rounding of the decimal weight, but in some other cases there might be other approximations.
> 
>     3. CASCADA runs over the solutions found and converts them to characteristics. For each characteristic (`ch_found`) CASCADA restores fractional parts of weights of the operations involved and determines the actual weight of the characteristic (`ch_found.ch_weight`, note that `ch_found.ch_weight >= target_weight`).
When a characteristic is found with `target_weight=X`, that means that a characteristic was found where the sum of the `bv_weight`s was X. However, CASCADA also computes the decimal weight of the characteristic (i.e., `ch_found.ch_weight`), and the decimal characteristic weight (which is a better aproximation that `bv_weight`) is the one used to compared with `target_weight`.
> 
> 
> Your example (`target_weight = 1`, `ch_found.ch_weight = 0`) does not match the reconstruction above. What is wrong?

The example `target_weight = 1`, `ch_found.ch_weight = 0` means that a characteristic was found with `bv_weight` 1 but with decimal weight 0.

**Comment by ranea** [comment]
> > Regarding the error in the second comment, does this also affect if the line new_final_weight = int(math.ceil(ch_found.ch_weight + self._error)) is used?
> 
> I have experimented with GOST (see #11). With
> 
> ```
> new_final_weight = int(math.ceil(ch_found.ch_weight + self._error)) 
> ```
> 
> I was unable to complete experiments and get to the problem lines of code every time I used an S-box with a non-integer weight.
> 
> An example:
> 
> ```
> from cascada.differential.difference import XorDiff
> from cascada.smt.chsearch import ChModelAssertType, PrintingMode 
> from cascada.smt.chsearch import round_based_ch_search
> from cascada.primitives import gost
> 
> Gost = gost.get_GOST_instance(gost.SBOXES_CB) 
> Gost.test()
> 
> def gost_da(initial_num_rounds, final_num_rounds, initial_weight=0):
>   iterator = round_based_ch_search(
>     Gost, initial_num_rounds, final_num_rounds, 
>     XorDiff, ChModelAssertType.ValidityAndWeight, "btor",
>     extra_chfinder_args={
>       "exclude_zero_input_prop": True, 
>       "printing_mode": PrintingMode.WeightsAndSrepr,
>       "solver_seed": 0},
>     extra_findnextchweight_args={"initial_weight": initial_weight}
>   )
>   for (num_rounds, ch) in iterator:
>     print(num_rounds, ":", ch.srepr())
> 
> gost_da(6, 6)
> ```

Can you create a new issue and post the error that you get (when keeping the `new_final_weight = int(math.ceil(ch_found.ch_weight + self._error)) `)? I think that this is problem is independent as the issue we are discussing here related to bit-vector and decimal weights.

**Comment by agievich** [comment]
> Can you create a new issue and post the error that you get (when keeping the `new_final_weight = int(math.ceil(ch_found.ch_weight + self._error))` )? I think that this is problem is independent as the issue we are discussing here related to bit-vector and decimal weights.

See #12.

**Comment by agievich** [comment]
Thanks for the explanation. So, as far as I understand, 

1. In a particular model, an operation `op` is described by an integer `bv_weight(op)` and real `decimal_weight(op)`. These characteristics are related to each other in a non-trivial way.

2. CASCADA uses `bv_weight(op)` when constructing an SMT problem of searching for a low-weight characteristic `ch`. The problem includes the restriction 
```
target_weight == \sum_{op \in ch} bv_weight(op).
```

3. If the problem is solved and `ch` is found, CASCADA determines
```
ch_weight == \sum_{op \in ch} decimal_weight(op).
```

4. It holds that `|target_weight - ch_weight| <= error`, where
```
error = \sum_{op \in cipher} |bv_weigth(op) - decimal_weight(op)|.
```

Therefore, to ensure that `ch_weight` is minimal, CASCADA processes `target_weight` up to
```
ceil(ch_weight + error)
```
(it seems that we can use `floor(ch_weight + error)` here). It can be expensive as `error` can be large and the number of solutions / characteristics to find and process increases rapidly as `target_weight` grows.

For example, in our experiments with GOST we could not obtain the final result, the characteristic of minimum weight, even for a rather small number of rounds. These experiments motivate this issue.

The possible solution, suggested at the very beginning, is to require that `bv_weight(op) <= decimal_weight(op)`. With this requirement, we need to process `target_weight` only up to
```
ceil(ch_weight).
```
This significantly reduces the search space.

> In some cases, the `bv_weight` is the rounding of the decimal weight, but in some other cases there might be other approximations. 

**Q**. Is it possible to require `bv_weight(op) <= decimal_weight(op)` everywhere?

**Comment by ranea** [comment]
Your explanation is a good summary of the behavior of CASCADA.

Here are my last remarks:

- using `ceil(ch_weight + error)` instead of `floor` is a minor optimization trick and should still ensure the optimal of the search as far as I remember
- the problem with `bv_weight(op) <= decimal_weight(op)` is that this relation does not hold for all the operation models implemented in CASCADA (e.g., for the XOR differential of the modular addition by a constant).

However, if you have a cipher, and you know that for all non-linear operations of the cipher it holds `bv_weight(op) <= decimal_weight(op)` (e.g., because the only non-linear operation is an S-box and you are using the minimum weight of the DDT entries), then you can still search for the characteristic with the minimum bit-vector weight efficiently by stopping the search (or increasing the number of rounds) as soon as you obtain a characteristic. For example:

```python
    iterator = round_based_ch_search(...)
    for (num_rounds, ch) in iterator:
        print(num_rounds, ":", ch.srepr())
        iterator.send(INCREMENT_NUM_ROUNDS)  # stop current num_rounds and increment by 1
```

**Comment by agievich** [comment]
The trick with

```python
    iterator.send(INCREMENT_NUM_ROUNDS)  # stop current num_rounds and increment by 1
```

doesn't work, since we don't know for sure whether the current best `ch_weight` is indeed the best. To get full guarantees, we have to wait for `target_weight = ceil(ch_weight)` (provided that `bv_weight(op) <= decimal_weight(op)`). The easiest way yo achieve such functionality is to rewrite `_new_final_weight()` as suggested in the very beginning. 

You wrote that the restriction `bv_weight(op) <= decimal_weight(op)` is not mandatory and we cannot change `_new_final_weight()` without taking into account the list of operations. Therefore, the issue has to be abandoned. 

Thanks again for the explanation!
