### ISSUE TITLE
issue with experimental diffvalchsearch.py module

### ISSUE THREAD

**Issue by PolikarpovSV** [ranea/CASCADA#6]
Hi,

there are 2 issues with experimental diffvalchsearch.py module:
1. Module dont work with last CASCADA commit (but work with prev commit):

Traceback (most recent call last):
  File "/home/user/CASCADA/diffvalchsearch_pcollapser.py", line 112, in <module>
    assert str(diff_ch_model.ssa) == str(a_ch_model.ssa).replace("Ap", "dp").replace("Ax", "dx").replace("Ck", "dk")
AssertionError

2. Module dont work with a bigger size models. For example: for two-three rounds of the pcollapserARX-16bit this module work fine, but fail if increasing num of the rounds to four. Same, if we increasing block_size to 32 bit - for two rounds work fine, but for more rounds - fail. Trying to increase the recursion limit and stack size didn't solve the problem. Used script you can find at: https://github.com/pruvad/CTCrypt2023

Log with this bug:
 
[recursion_bug.txt](https://github.com/ranea/CASCADA/files/11413374/recursion_bug.txt)

With best regards, 
Polikarpov S.V.

**Comment by ranea** [comment]
Thanks for the feedback.

Regarding the first issue, I noticed the bug and I fixed it.

Regarding the second, it seems that the simplification code is taking too much time trying to simplify long transitions in `assign_outdiff2op_model`. For example, in the `Symbolic difference transitions: EncryptionChModel(cipher=pcollapserARXcipher_3R, ...)`, there are long transitions like

```
(XorDiff(dx431), XorModelBvAdd([XorDiff(((dx26 :: dx25) ^ ((dx46 <<< 1) :: (dx45 <<< 1)) ^ ((dx69 <<< 2) :: (dx68 <<< 2)) ^ ((dx92 <<< 3) :: (dx91 <<< 3)) ^ (dx119 :: dx118) ^ ((dx138 <<< 1) :: (dx137 <<< 1)) ^ ((dx161 <<< 2) :: (dx160 <<< 2)) ^ (dx215 :: dx214) ^ ((dx235 <<< 1) :: (dx234 <<< 1)) ^ ((dx281 <<< 3) :: (dx280 <<< 3)) ^ (dx312 :: dx311) ^ ((dx355 <<< 2) :: (dx354 <<< 2)) ^ ((dx378 <<< 3) :: (dx377 <<< 3)) ^ dp0)[3:]), XorDiff(((((dx26 :: dx25) ^ ((dx46 <<< 1) :: (dx45 <<< 1)) ^ ((dx69 <<< 2) :: (dx68 <<< 2)) ^ ((dx92 <<< 3) :: (dx91 <<< 3)) ^ (dx119 :: dx118) ^ ((dx138 <<< 1) :: (dx137 <<< 1)) ^ ((dx161 <<< 2) :: (dx160 <<< 2)) ^ (dx215 :: dx214) ^ ((dx235 <<< 1) :: (dx234 <<< 1)) ^ ((dx281 <<< 3) :: (dx280 <<< 3)) ^ (dx312 :: dx311) ^ ((dx355 <<< 2) :: (dx354 <<< 2)) ^ ((dx378 <<< 3) :: (dx377 <<< 3)) ^ dp0)[3:]) <<< 1) ^ (((dx26 :: dx25) ^ ((dx46 <<< 1) :: (dx45 <<< 1)) ^ ((dx69 <<< 2) :: (dx68 <<< 2)) ^ ((dx92 <<< 3) :: (dx91 <<< 3)) ^ (dx119 :: dx118) ^ ((dx138 <<< 1) :: (dx137 <<< 1)) ^ ((dx161 <<< 2) :: (dx160 <<< 2)) ^ (dx215 :: dx214) ^ ((dx235 <<< 1) :: (dx234 <<< 1)) ^ ((dx281 <<< 3) :: (dx280 <<< 3)) ^ (dx312 :: dx311) ^ ((dx355 <<< 2) :: (dx354 <<< 2)) ^ ((dx378 <<< 3) :: (dx377 <<< 3)) ^ dp0)[:4]))]))
```

To prevent this simplification you can do the following:

First, disable simplification by wrapping all the code under the context `Simplification(False)`

```
import functools
import warnings

from cascada.bitvector.context import Simplification
from cascada.bitvector.operation import BvComp

[...]

import sys
sys.setrecursionlimit(100000000)  

if __name__ == '__main__':
    with Simplification(False):
        [...]
```

Second, you can shorten the transitions by adding intermediate variables to the cipher (which will add intermediate variables to the model). You can create temporary intermediate variables by using the operation `BvIdentity`. For example, you can add intermediate variables in the transitions of the modular addition (that correspond to the longest transitions) by replacing modular additions like these `a = a + at` into `a = (BvIdentity(a) + BvIdentity(at))`.

**Comment by PolikarpovSV** [comment]
Thanks a lot,
the second option solved the problem, the model generation time fell from 11 hours to several minutes (I added intermediate variables inside the round by BvIdentity() ).
The first option only makes it worse, I would not recommend using it (disable simplification).

But there are a few more problems with the models.
When find RXDiff characteristic, we get next results:
Command (for block size = 16 bit):

`python3.11 test_collapser.py rxdiff -b 16 -f 1 -l 2`

```
// variable at "test_collapser.py":
// OLD_STYLE_ARX_FUNC = 0
```

```
1 : Ch(ks_ch=Ch(w=0, id=f f f f, od=f f f f), enc_ch=Ch(w=61.60, id=4 b 3 c, od=0 2 4 a))
2 : Ch(ks_ch=Ch(w=0, id=b 4 c 3 8 6 6 a, od=b 4 c 3 8 6 6 a), enc_ch=Ch(w=111.4, id=0 0 0 0, od=0 0 4 d))
```

`// OLD_STYLE_ARX_FUNC = 1`

```
1 : Ch(ks_ch=Ch(w=0, id=f f f f, od=f f f f), enc_ch=Ch(w=233.6, id=4 a 2 0, od=0 0 4 6))
2 : Ch(ks_ch=Ch(w=0, id=b 5 d 7 a 8 c c, od=b 5 d 7 a 8 c c), enc_ch=Ch(w=458.4, id=0 0 0 0, od=0 0 8 4))
```

In these cases, only the description of the sboxARX functions differs: 
in the first case, this function is described using the operations **RotateLeft()**, **"+"**, **Extract()** and **Concat()**, 
in the second case, using the operations like **const1 = (constant >> wordsize) & mask** to use subwords from a word and **arxout = (a & mask) ^ ((b & mask) << wordsize)** to concatenate subwords to a word, and **ROTL()** to rotate a subwords.

If we check the correctness of the implementation of the function, 

`python3.11 test_collapser.py verify_implementation`

then in both cases there will be a correct result. But the weight value differs several times.
I would use the first option, but when using the full ARX-function (for block size 32 and more), an error occurs:

`python3.11 test_collapser.py rxdiff -b 32 -f 1 -l 2`

 ```
 File "/home/user/CASCADA/cascada/differential/difference.py", line 539, in propagate
    raise ValueError(msg)
ValueError: invalid arguments: op=Extract_{·, 3, 0}, input_diff=[RXDiff(dp0 ^ dmk0_out ^ 0xde)]
```
As I think, due to the presence of the operation **Extract()** and **Concat()**

In addition to this, I am concerned about the weights being too high in both cases (w > 1500 for a block size = 32 bit). 
Are these values calculated correctly? Maybe there is a problem described in https://eprint.iacr.org/2022/135.pdf

**Comment by ranea** [comment]
The error `ValueError: invalid arguments: op=Extract_{·, 3, 0}, input_diff=[RXDiff(dp0 ^ dmk0_out ^ 0xde)]` happens because the propagation of rotational-XOR differences through the operations `Extract` or `Concat` is not supported, in other words, `RXDiff` cannot be used with ciphers containing these operations. 

  

Regarding the problem of getting different weights for different representations of `sboxARX`, this is because a characteristic and its probability/weight depends on the *cipher representation* (the sequence of operations used to represent of the cipher). So different cipher representations lead to different sequences of operations, leading to different sequences of differential transitions, and thus leading to different characteristics. In your case, for the first representation `RotateLeft` is "linear" w.r.t `RXDiff`, but the shifts and the AND in your second representation are adding extra non-linear transitions and thus increasing the weight. 

  

This is unfortunately a drawback of any method that search for characteristics. What it is usually done is practice is to search for the best characteristic `a0 -> a1 -> ... -> an` (which is dependent on the cipher representation) to estimate the probability of the best differential `a0 -> a1` (that only depends on the input and output differences and thus not on the cipher representation). 

  

However, estimating the probability of the best differential accurately can only be done when the Markov cipher assumption holds, but in your case, it seems that the assumption that the intermediate differential probabilities/weights of a characteristic are independent does not hold. That is why you get those huge weights, but the weight of the corresponding differentials (with only input and output differences) should be much smaller. 

  

One possibility to get characteristic weights that are closer to input-output weights is to use less non-linear operations to represent a cipher.  Also, if you see that `sboxARX` is the component that increase the weight the most, you could represent `sboxARX` by a single bit-vector operation (as a `SecondaryOperation`) and assign a weak model to `sboxARX`, but then you would need to estimate the `XorDiff` or `RXDiff` properties of this operation separately.

**Comment by PolikarpovSV** [comment]
thanks a lot for the detailed answer.
I think this issue can be closed.
